### ISSUE TITLE
White border around main editor area

### ISSUE THREAD

**Issue by geniot** [freeplane/shtml#2]
White border is not obvious until you set the background of the edited document to some other color than white. Eg.:
```
<html><head>
<style>
  body {background-color: black;padding:0;margin:0;}
 html {background-color: black;padding:0;margin:0;}
</style>
  </head>
...
```
Do you know where the white border comes from and how to get rid of it? 
Thanks.

**Comment by dpolivaev** [comment]
> Do you know where the white border comes from and how to get rid of it?

No I don't. Sorry.

**Comment by geniot** [comment]
Ok. I actually started to experiment with borders and here is the fix (if non-empty borders are considered a bug at all):
```
            getDocumentPane().getEditor().setBorder(new EmptyBorder(0,0,0,0));
            JViewport viewport = (JViewport) getDocumentPane().getEditor().getParent();
            JScrollPane scrollPane = (JScrollPane) viewport.getParent();
            scrollPane.setBorder(new EmptyBorder(0,0,0,0));
```

So by default JEditorPane has some EmptyBorder(2,2,2,2) and JScrollPane has a line border.
